version: "3.8"

services:
  drawer:
    build: ./
    volumes:
      - "./drawer:/var/www/html"
    ports:
      - "8080:80"
  
  sorter:
    build: ./
    volumes:
      - "./sorter:/var/www/html"
    ports:
      - "8081:80"

  shellcomands:
    build: ./
    volumes:
      - "./shellcomands:/var/www/html"
    ports:
      - "8082:80"
  